const CHISPA_CODE_KEY='chispa-household-code-v1';
const MAX_FILE_BYTES=2000000;
const FILE_TYPES=new Set(['image/jpeg','image/png','image/webp','application/pdf']);
let decorating=false;

function fileLang(){return document.documentElement.lang?.startsWith('en')?'en':(document.querySelector('#lang')?.textContent==='ES'?'en':'es')}
function ft(es,en){return fileLang()==='es'?es:en}
async function derivedHouseholdId(){const code=localStorage.getItem(CHISPA_CODE_KEY);if(!code)return null;const bytes=new TextEncoder().encode(`chispa:v1:${code.trim().toLowerCase()}`),hash=await crypto.subtle.digest('SHA-256',bytes);return'chispa-'+[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function fileToast(message){const d=document.createElement('div');d.className='toast';d.textContent=message;document.body.append(d);setTimeout(()=>d.remove(),2400)}
function dataUrlBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||'').split(',')[1]||'');r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
async function prepareFile(file){if(file.size<=MAX_FILE_BYTES)return file;if(!file.type.startsWith('image/'))return file;try{const bmp=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bmp.width*scale));canvas.height=Math.max(1,Math.round(bmp.height*scale));canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close?.();const blob=await new Promise(ok=>canvas.toBlob(ok,'image/jpeg',.78));if(!blob)return file;return new File([blob],String(file.name||'photo').replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg',lastModified:Date.now()})}catch{return file}}
function fieldInput(kind){return document.querySelector(`input[data-field="${kind}"]`)}
function updateField(kind,url){const input=fieldInput(kind);if(!input)return;input.value=url;input.dispatchEvent(new Event('change',{bubbles:true}));input.dispatchEvent(new Event('input',{bubbles:true}))}
function storedFileId(value){if(!value)return null;try{const u=new URL(value,location.origin);return u.pathname==='/api/files'?u.searchParams.get('fileId'):null}catch{return null}}
async function deleteStoredFile(householdId,fileId){if(!householdId||!fileId)return false;try{const r=await fetch('/api/files',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({householdId,fileId})});return r.ok}catch{return false}}
async function uploadFile(input){let file=input.files?.[0];const kind=input.dataset.uploadKind,itemId=input.dataset.id;if(!file)return;if(!FILE_TYPES.has(file.type)){fileToast(ft('Usa JPG, PNG, WebP o PDF.','Use JPG, PNG, WebP or PDF.'));input.value='';return}file=await prepareFile(file);if(file.size>MAX_FILE_BYTES){fileToast(ft('El archivo debe pesar menos de 2 MB. Las fotos grandes se comprimen automáticamente.','File must be under 2 MB. Large photos are compressed automatically.'));input.value='';return}const householdId=await derivedHouseholdId();if(!householdId){fileToast(ft('Conecta Nube compartida primero.','Connect Shared Cloud first.'));input.value='';document.querySelector('#cloud-pill')?.click();return}const previous=fieldInput(kind)?.value||'',previousId=storedFileId(previous),button=input.closest('.upload-control')?.querySelector('.upload-button');if(button){button.setAttribute('aria-disabled','true');button.style.pointerEvents='none';button.childNodes[0].textContent=ft('Subiendo…','Uploading…')}try{const data=await dataUrlBase64(file),r=await fetch('/api/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({householdId,itemId,kind,name:file.name,type:file.type,data})}),out=await r.json();if(!r.ok||!out.url)throw new Error(out.error||'upload_failed');updateField(kind,out.url);if(previousId&&previousId!==out.fileId)await deleteStoredFile(householdId,previousId);fileToast(ft('Archivo guardado en la nube privada.','File saved to private cloud storage.'))}catch(e){console.error('Chispa file upload',e);fileToast(ft('No se pudo subir. Tus datos locales siguen seguros.','Upload failed. Your local data is still safe.'))}finally{input.value='';if(button){button.removeAttribute('aria-disabled');button.style.pointerEvents='';button.childNodes[0].textContent=button.dataset.label||ft('Subir archivo','Upload file')}}}
async function removeFile(kind,button){const input=fieldInput(kind),value=input?.value||'',fileId=storedFileId(value),householdId=await derivedHouseholdId();if(!value)return;if(!confirm(ft('¿Quitar este archivo del artículo?','Remove this file from the item?')))return;if(fileId&&householdId){button.disabled=true;const ok=await deleteStoredFile(householdId,fileId);button.disabled=false;if(!ok){fileToast(ft('No se pudo borrar el archivo de la nube.','Could not delete the cloud file.'));return}}updateField(kind,'');fileToast(ft('Archivo eliminado.','File removed.'))}
function makeControl(kind,id,value){const wrap=document.createElement('div');wrap.className='upload-control';const labels={photo:[ft('Subir foto','Upload photo'),'image/*'],receipt:[ft('Subir recibo','Upload receipt'),'image/*,application/pdf'],warranty:[ft('Subir garantía','Upload warranty'),'image/*,application/pdf']},[label,accept]=labels[kind];wrap.innerHTML=`<label class="upload-button secondary" data-label="${label}">${label}<input type="file" accept="${accept}" data-upload-kind="${kind}" data-id="${id}" hidden></label>${value?`<a class="file-open" href="${value.replace(/"/g,'&quot;')}" target="_blank" rel="noopener">${ft('Abrir archivo','Open file')} ↗</a><button type="button" class="link danger-link file-remove">${ft('Eliminar archivo','Remove file')}</button>`:''}<small>${ft('JPG, PNG, WebP o PDF · máx. 2 MB · fotos grandes se comprimen','JPG, PNG, WebP or PDF · max 2 MB · large photos compress automatically')}</small>`;wrap.querySelector('input').addEventListener('change',e=>uploadFile(e.currentTarget));wrap.querySelector('.file-remove')?.addEventListener('click',e=>removeFile(kind,e.currentTarget));return wrap}
function enhanceItemFiles(){const photo=fieldInput('photo');if(!photo||document.querySelector('.chispa-file-controls'))return;const form=photo.closest('.form');if(!form)return;form.classList.add('chispa-file-controls');for(const kind of ['photo','receipt','warranty']){const input=fieldInput(kind);if(!input)continue;input.closest('label')?.insertAdjacentElement('afterend',makeControl(kind,input.dataset.id,input.value))}}
function refreshFileLinks(){document.querySelectorAll('.upload-control').forEach(wrap=>{const kind=wrap.querySelector('input')?.dataset.uploadKind,input=kind&&fieldInput(kind);if(!input)return;const open=wrap.querySelector('.file-open'),remove=wrap.querySelector('.file-remove');if(input.value&&!open){const a=document.createElement('a');a.className='file-open';a.href=input.value;a.target='_blank';a.rel='noopener';a.textContent=ft('Abrir archivo','Open file')+' ↗';wrap.querySelector('small')?.before(a);const b=document.createElement('button');b.type='button';b.className='link danger-link file-remove';b.textContent=ft('Eliminar archivo','Remove file');b.addEventListener('click',e=>removeFile(kind,e.currentTarget));a.after(b)}else if(!input.value){open?.remove();remove?.remove()}})}
function fixCopy(){const docNote=document.querySelector('.doc-grid + .muted');if(docNote)docNote.textContent=ft('Fotos, recibos y garantías se guardan de forma privada cuando conectas Nube compartida. Los números de serie y fechas de devolución también viajan con el hogar.','Photos, receipts and warranties are stored privately when Shared Cloud is connected. Serial numbers and return dates sync with the household too.');document.querySelectorAll('.setting-grid p').forEach(p=>{const s=p.textContent||'';if(s.includes('Supabase autoalojado')||s.includes('self-hosted Supabase'))p.textContent=ft('IndexedDB guarda automáticamente en este dispositivo. Nube compartida sincroniza el hogar entre dispositivos cuando usas el mismo código.','IndexedDB autosaves on this device. Shared Cloud syncs the household across devices when you use the same code.');if(s.includes('edición compartida se activa')||s.includes('Shared editing activates'))p.textContent=ft('Crea enlaces de solo lectura, resúmenes para WhatsApp o usa compartir del teléfono. Para edición compartida, conecta ambos dispositivos con el mismo código de Nube compartida.','Create read-only links, WhatsApp summaries or use the phone share sheet. For shared editing, connect both devices with the same Shared Cloud code.')}})}
function decorateFiles(){if(decorating)return;decorating=true;try{enhanceItemFiles();refreshFileLinks();fixCopy()}finally{decorating=false}}
new MutationObserver(()=>queueMicrotask(decorateFiles)).observe(document.documentElement,{childList:true,subtree:true});
setTimeout(decorateFiles,400);
